# copied and adapted from https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/
---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(levelname)s - %(asctime)s - %(name)s - %(module) - %(funcName) - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: info.log
        encoding: utf8

    error_file_handler:
        class: logging.FileHandler
        level: ERROR
        formatter: simple
        filename: errors.log
        encoding: utf8

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]
...
